// This file will be auto-generated by Supabase CLI
// For now, we'll define the types manually based on our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      farmers: {
        Row: {
          id: string
          full_name: string
          phone: string
          rsbsa_number: string | null
          date_of_birth: string | null
          address: string | null
          barangay: string | null
          zip_code: string | null
          farm_type: string | null
          farm_location: string | null
          organization: string | null
          date_of_office_visit: string
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          full_name: string
          phone: string
          rsbsa_number?: string | null
          date_of_birth?: string | null
          address?: string | null
          barangay?: string | null
          zip_code?: string | null
          farm_type?: string | null
          farm_location?: string | null
          organization?: string | null
          date_of_office_visit?: string
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          full_name?: string
          phone?: string
          rsbsa_number?: string | null
          date_of_birth?: string | null
          address?: string | null
          barangay?: string | null
          zip_code?: string | null
          farm_type?: string | null
          farm_location?: string | null
          organization?: string | null
          date_of_office_visit?: string
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      transactions: {
        Row: {
          id: string
          farmer_id: string
          transaction_type: string
          amount: number | null
          description: string | null
          notes: string | null
          office_visit_at: string
          created_at: string
        }
        Insert: {
          id?: string
          farmer_id: string
          transaction_type: string
          amount?: number | null
          description?: string | null
          notes?: string | null
          office_visit_at?: string
          created_at?: string
        }
        Update: {
          id?: string
          farmer_id?: string
          transaction_type?: string
          amount?: number | null
          description?: string | null
          notes?: string | null
          office_visit_at?: string
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
