export const ALL_TRANSACTION_TYPES = [
  "Application for crop Insurance",
  "Application for livestock insurance",
  "Filing of damage report",
  "Filling for reconsideration letter",
  "Request for certificate (loan, rsbsa no., land area, plant identification, others)",
  "Application for RSBSA enrollment",
  "Application for request for change and information in RSBSA",
  "Application for change of personal information",
  "Requests for schedule subsidy",
  "Requests for fertilizer subsidy",
  "Availment of PCIC indemnity check",
  "Follow up of insurance status",
  "Requests for technical assistance",
  "Attend meetings",
  "Attend orientation",
  "Attend training",
  "Requests for research consultant",
];
